# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showCoffeeInfoList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.showCoffeeInfoList.setGeometry(QtCore.QRect(10, 70, 781, 481))
        self.showCoffeeInfoList.setObjectName("showCoffeeInfoList")
        self.getCoffeeInfoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getCoffeeInfoButton.setGeometry(QtCore.QRect(380, 20, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.getCoffeeInfoButton.setFont(font)
        self.getCoffeeInfoButton.setObjectName("getCoffeeInfoButton")
        self.changeCoffeeInformationButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changeCoffeeInformationButton.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.changeCoffeeInformationButton.setFont(font)
        self.changeCoffeeInformationButton.setObjectName("changeCoffeeInformationButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.getCoffeeInfoButton.setText(_translate("MainWindow", "Вывести информацию о кофе"))
        self.changeCoffeeInformationButton.setText(_translate("MainWindow", "Изменить ифнормацию о кофе"))
